In [ ]:


a = [0]
a1 = a * 10
print(str(id(a))+":%s" %(a))
print(str(id(a1)) + ":%s" %(a1))

a2 = a1*10
print(a1)
print(a2)


a3 = [[0 for x in range(10)] for x in range(10)]
print(a3)

In [ ]:
# 函数运行装饰器
def decorate_func_time(func):
    from datetime import datetime as dt 
    def inner(*args, **kwargs):
        start = dt.now()
        ret = func(*args, **kwargs)
        delta = dt.now() - start 
        print(func.__name__ + ' elapsed time:' + str(delta.microseconds))
        return ret 
    return inner 

@decorate_func_time
def func1(num):
    a = [[0] * num] * num
    print(type(a))
#     print(a)

@decorate_func_time
def func2(num):
    a = [[0 for x in range(num)] for x in range(num)]
    print(type(a))
#     print(a)
    
import numpy as np
@decorate_func_time
def func3(num):
    a = np.zeros((num,num))
    print(type(a))




func1(100)
func2(100)
func3(100)

In [ ]:
import numpy as np
a = np.arange(10,19).reshape((3,3))
print(a)
print(a[0,:1])
print(a[:,0])
print(a[0:2,0])
print(a[0,:])

for item in a.flat:
    print(item)
    
np.apply_along_axis(np.mean, axis=0, arr=a)
np.apply_along_axis(np.mean, axis=1, arr=a)

def foo(x):
    return x/2

np.apply_along_axis(foo, axis=0, arr=a)


# print(a[:,0])

In [ ]:
# 条件和布尔数组
import numpy as np
A = np.random.random((4,4)) # 由0到1之间的随机4x4数组
A
A < 0.5
A[A<0.5]

In [ ]:
# 形状变形
import numpy as np
a = np.random.random(12)
A = a.reshape((3,4))
print(A)
# A
# a
# a.shape = (4,3) # 通过改变a的形状直接改变
# a

Aa = A.transpose()
print(Aa)

In [ ]:
# 连接数组
A = np.ones((3,3))
B = np.zeros((3,3))
np.vstack((A,B)) # 垂直入栈操作
np.hstack((A,B)) # 水平入栈操作

In [ ]:
a = np.array([0,1,2])
b = np.array([3,4,5])
c = np.array([6,7,8])
np.column_stack((a,b,c)) # 列入栈
np.row_stack((a,b,c)) # 行入栈

In [ ]:
A = np.arange(16).reshape((4,4))
print(A)
[B,C] = np.vsplit(A,2) # 垂直切分，把数组按照高度分为两部分
# print(B)
[D,E] = np.hsplit(A,2) # 水平切分，把数组按照宽度切分为两部分
# print(D)
[A1,A2,A3] = np.split(A,[1,3], axis=1)
print(A1)
print(A2)
print(A3)

In [115]:
a = np.array([1,2,3,4])
b = a
print(b)
a[2] = 0
# b

c = a[0:2]
c
a[0] = 0
c

d = a.copy()
d
a[0] = 100
d
print(a)

[1 2 3 4]
[100   2   0   4]


In [119]:
m = np.arange(6).reshape(3,1,2) # 3x1x2
n = np.arange(6).reshape(3,2,1) # 3x2x1

structured = np.array([(1, 'First', 0.5, 1+2j), (2, 'Second', 1.3, 2-2j),
                      (3, 'Third', 0.8, 1+3j)], dtype=('i2,a6,f4,c8'))
structured

array([(1, b'First', 0.5, 1.+2.j), (2, b'Second', 1.3, 2.-2.j),
       (3, b'Third', 0.8, 1.+3.j)],
      dtype=[('f0', '<i2'), ('f1', 'S6'), ('f2', '<f4'), ('f3', '<c8')])

In [124]:
# data = np.random.random((3,3))
# print(data)
# np.save('saved_data', data)
loaded_data = np.load('saved_data.npy')
loaded_data

array([[0.94015526, 0.81096065, 0.73981146],
       [0.42322284, 0.37661001, 0.90465137],
       [0.84440177, 0.14705889, 0.19552337]])

In [127]:
data2 = np.genfromtxt('data2.csv', delimiter=',', names=True)
print(data2)
print(data2['id'])
print(data2[0])

[(1., 123., 1.4, 23.) (2., 110., nan, 18.) (3.,  nan, 2.1, 19.)]
[1. 2. 3.]
(1., 123., 1.4, 23.)


In [131]:
a = np.random.random(10)
a
import random
t = random.randrange(1,10)
t

6

In [132]:
help(random.randint)

Help on method randint in module random:

randint(a, b) method of random.Random instance
    Return random integer in range [a, b], including both end points.



In [134]:
headers = ("User-Agent",
"Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) CriOS/56.0.2924.75 Mobile/14E5239e Safari/602.1")

type(headers)

tuple