In [19]:
# 工作分配
from pandas import DataFrame
import numpy as np

data = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]])
print(data)

n1 = np.random.randint(10, size=5)
print(n1)

list = []
for i in range(5):
    list.append(np.random.randint(10, size=5))
    
print(list)

data = np.array(list)
print(data)


# print(np.max(data[1]))        

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
[8 7 2 4 2]
[array([3, 6, 1, 1, 5]), array([1, 4, 5, 3, 7]), array([8, 4, 1, 5, 1]), array([8, 6, 7, 4, 5]), array([8, 9, 5, 2, 2])]
[[3 6 1 1 5]
 [1 4 5 3 7]
 [8 4 1 5 1]
 [8 6 7 4 5]
 [8 9 5 2 2]]
